//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogsite.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string contents { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
    
        public virtual post post { get; set; }
        public virtual user user { get; set; }
    }
}
